NUNICODE_VERSION = 1.6
NUNICODE_SITE = https://bitbucket.org/alekseyt/nunicode/get
NUNICODE_SOURCE = nunicode_$(NUNICODE_VERSION).tar.bz2
NUNICODE_INSTALL_STAGING = YES
NUNICODE_LICENSE = MIT
NUNICODE_LICENSE_FILES = LICENSE

NUNICODE_DEPENDENCIES += sqlite

NUNICODE_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
NUNICODE_CONF_OPTS += -DCMAKE_CXX_FLAGS=-fPIC

$(eval $(cmake-package))
